# Project Pythia Notebook Template

Let's start here! If you can directly link to an image relevant to your notebook, such as [canonical logos](https://github.com/numpy/numpy/blob/main/doc/source/_static/numpylogo.svg), do so here at the top of your notebook. You can do this with MyST Markdown syntax, outlined in [this MyST guide](https://mystmd.org/guide/figures), or you edit this cell to see a demonstration. **Be sure to include `alt` text for any embedded images to make your content more accessible.**

```{image} ../thumbnails/thumbnail.png
:alt: Project Pythia logo
:width: 200px
```

Next, title your notebook appropriately with a top-level Markdown header, `#` (see the very first cell above). Do not use this level header anywhere else in the notebook. Our book build process will use this title in the navbar, table of contents, etc. Keep it short, keep it descriptive. 

Follow this with a `---` cell to visually distinguish the transition to the prerequisites section.

---

## Overview
If you have an introductory paragraph, lead with it here! Keep it short and tied to your material, then be sure to continue into the required list of topics below,

1. This is a numbered list of the specific topics
1. These should map approximately to your main sections of content
1. Or each second-level, `##`, header in your notebook
1. Keep the size and scope of your notebook in check
1. And be sure to let the reader know up front the important concepts they'll be leaving with

## Prerequisites
This section was inspired by [this template](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/templates/chapter-template/chapter-landing-page.md) of the wonderful [The Turing Way](https://the-turing-way.netlify.app) Jupyter Book.

Following your overview, tell your reader what concepts, packages, or other background information they'll **need** before learning your material. Tie this explicitly with links to other pages here in Foundations or to relevant external resources. Remove this body text, then populate the Markdown table, denoted in this cell with `|` vertical brackets, below, and fill out the information following. In this table, lay out prerequisite concepts by explicitly linking to other Foundations material or external resources, or describe generally helpful concepts.

Label the importance of each concept explicitly as **helpful/necessary**.

| Concepts | Importance | Notes |
| --- | --- | --- |
| [Intro to Cartopy](https://foundations.projectpythia.org/core/cartopy/cartopy) | Necessary | |
| [Understanding of NetCDF](https://foundations.projectpythia.org/core/data-formats/netcdf-cf) | Helpful | Familiarity with metadata structure |
| Project management | Helpful | |

- **Time to learn**: estimate in minutes. For a rough idea, use 5 mins per subsection, 10 if longer; add these up for a total. Safer to round up and overestimate.
- **System requirements**:
    - Populate with any system, version, or non-Python software requirements if necessary
    - Otherwise use the concepts table above and the Imports section below to describe required packages as necessary
    - If no extra requirements, remove the **System requirements** point altogether

---

## Imports

In [1]:
import duckdb
from datetime import datetime

## Your first content section

This is where you begin your first section of material, loosely tied to your objectives stated up front. Tie together your notebook as a narrative, with interspersed Markdown text, images, and more as necessary,

In [2]:
base = "https://data.source.coop/dynamical/asos-parquet"
urls = [f"{base}/year={y}/data.parquet" for y in range(1940, datetime.now().year + 1)]

In [3]:
urls

['https://data.source.coop/dynamical/asos-parquet/year=1940/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1941/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1942/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1943/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1944/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1945/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1946/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1947/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1948/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1949/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1950/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1951/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1952/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1953/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1954/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1955/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1956/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1957/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1958/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1959/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1960/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1961/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1962/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1963/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1964/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1965/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1966/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1967/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1968/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1969/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1970/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1971/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1972/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1973/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1974/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1975/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1976/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1977/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1978/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1979/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1980/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1981/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1982/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1983/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1984/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1985/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1986/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1987/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1988/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1989/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1990/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1991/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1992/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1993/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1994/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1995/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1996/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1997/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1998/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=1999/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2000/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2001/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2002/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2003/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2004/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2005/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2006/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2007/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2008/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2009/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2010/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2011/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2012/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2013/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2014/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2015/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2016/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2017/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2018/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2019/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2020/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2021/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2022/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2023/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2024/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2025/data.parquet',
 'https://data.source.coop/dynamical/asos-parquet/year=2026/data.parquet']

### A content subsection
Divide and conquer your objectives with Markdown subsections, which will populate the helpful navbar in Jupyter Lab and here on the Jupyter Book!

In [8]:
yr2526 = urls[-2:]

In [10]:
dfALB = duckdb.execute("""
    SELECT *
    FROM read_parquet($1, hive_partitioning=true)
    WHERE station = 'ALB'
    ORDER BY valid
""", [yr2526]).fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [11]:
dfALB

,station,valid,longitude,latitude,tmpf,tmpc,dwpf,dwpc,relh,drct,...,state,name,elevation,country,county,wfo,tzname,geometry,bbox,year
0,ALB,2025-01-01 00:00:00+00:00,-73.8036,42.7576,41.0,5.00,31.0,-0.56,67.30,0.0,...,NY,ALBANY COUNTY ARPT,89.0,US,Albany,ALY,America/New_York,"[1, 1, 0, 0, 0, 51, 196, 177, 46, 110, 115, 82...","{'xmin': -73.8036, 'ymin': 42.7576, 'xmax': -7...",2025
1,ALB,2025-01-01 00:51:00+00:00,-73.8036,42.7576,41.0,5.00,32.0,0.00,70.08,0.0,...,NY,ALBANY COUNTY ARPT,89.0,US,Albany,ALY,America/New_York,"[1, 1, 0, 0, 0, 51, 196, 177, 46, 110, 115, 82...","{'xmin': -73.8036, 'ymin': 42.7576, 'xmax': -7...",2025
2,ALB,2025-01-01 01:51:00+00:00,-73.8036,42.7576,41.0,5.00,31.0,-0.56,67.30,340.0,...,NY,ALBANY COUNTY ARPT,89.0,US,Albany,ALY,America/New_York,"[1, 1, 0, 0, 0, 51, 196, 177, 46, 110, 115, 82...","{'xmin': -73.8036, 'ymin': 42.7576, 'xmax': -7...",2025
3,ALB,2025-01-01 02:51:00+00:00,-73.8036,42.7576,41.0,5.00,31.0,-0.56,67.30,0.0,...,NY,ALBANY COUNTY ARPT,89.0,US,Albany,ALY,America/New_York,"[1, 1, 0, 0, 0, 51, 196, 177, 46, 110, 115, 82...","{'xmin': -73.8036, 'ymin': 42.7576, 'xmax': -7...",2025
4,ALB,2025-01-01 03:51:00+00:00,-73.8036,42.7576,39.0,3.89,30.0,-1.11,69.85,320.0,...,NY,ALBANY COUNTY ARPT,89.0,US,Albany,ALY,America/New_York,"[1, 1, 0, 0, 0, 51, 196, 177, 46, 110, 115, 82...","{'xmin': -73.8036, 'ymin': 42.7576, 'xmax': -7...",2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15957,ALB,2026-06-14 15:51:00+00:00,-73.8036,42.7576,76.0,24.44,61.0,16.11,59.78,160.0,...,NY,ALBANY COUNTY ARPT,89.0,US,Albany,ALY,America/New_York,"[1, 1, 0, 0, 0, 51, 196, 177, 46, 110, 115, 82...","{'xmin': -73.8036, 'ymin': 42.7576, 'xmax': -7...",2026
15958,ALB,2026-06-14 16:51:00+00:00,-73.8036,42.7576,78.0,25.56,62.0,16.67,57.97,170.0,...,NY,ALBANY COUNTY ARPT,89.0,US,Albany,ALY,America/New_York,"[1, 1, 0, 0, 0, 51, 196, 177, 46, 110, 115, 82...","{'xmin': -73.8036, 'ymin': 42.7576, 'xmax': -7...",2026
15959,ALB,2026-06-14 17:51:00+00:00,-73.8036,42.7576,81.0,27.22,64.0,17.78,56.37,160.0,...,NY,ALBANY COUNTY ARPT,89.0,US,Albany,ALY,America/New_York,"[1, 1, 0, 0, 0, 51, 196, 177, 46, 110, 115, 82...","{'xmin': -73.8036, 'ymin': 42.7576, 'xmax': -7...",2026
15960,ALB,2026-06-14 18:51:00+00:00,-73.8036,42.7576,83.0,28.33,63.0,17.22,51.02,170.0,...,NY,ALBANY COUNTY ARPT,89.0,US,Albany,ALY,America/New_York,"[1, 1, 0, 0, 0, 51, 196, 177, 46, 110, 115, 82...","{'xmin': -73.8036, 'ymin': 42.7576, 'xmax': -7...",2026
15961,ALB,2026-06-14 19:51:00+00:00,-73.8036,42.7576,83.0,28.33,64.0,17.78,52.84,170.0,...,NY,ALBANY COUNTY ARPT,89.0,US,Albany,ALY,America/New_York,"[1, 1, 0, 0, 0, 51, 196, 177, 46, 110, 115, 82...","{'xmin': -73.8036, 'ymin': 42.7576, 'xmax': -7...",2026

In [13]:
dfALB.columns

Index(['station', 'valid', 'longitude', 'latitude', 'tmpf', 'tmpc', 'dwpf',
       'dwpc', 'relh', 'drct', 'sknt', 'gust', 'alti', 'mslp', 'vsby', 'p01i',
       'p01m', 'state', 'name', 'elevation', 'country', 'county', 'wfo',
       'tzname', 'geometry', 'bbox', 'year'],
      dtype='object')

In [4]:
df = duckdb.execute("""
    SELECT valid, station, name, country, tmpf, dwpf, sknt, p01i
    FROM read_parquet($1, hive_partitioning=true)
    WHERE station = 'ALB'
    ORDER BY valid
""", [urls]).fetchdf()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [5]:
df

,valid,station,name,country,tmpf,dwpf,sknt,p01i
0,1945-01-01 11:00:00+00:00,ALB,ALBANY COUNTY ARPT,US,37.0,36.0,15.0,NaN
1,1945-01-01 12:00:00+00:00,ALB,ALBANY COUNTY ARPT,US,37.0,36.0,14.0,NaN
2,1945-01-01 13:00:00+00:00,ALB,ALBANY COUNTY ARPT,US,38.0,38.0,10.0,NaN
3,1945-01-01 14:00:00+00:00,ALB,ALBANY COUNTY ARPT,US,40.0,40.0,10.0,NaN
4,1945-01-01 15:00:00+00:00,ALB,ALBANY COUNTY ARPT,US,40.0,40.0,10.0,NaN
...,...,...,...,...,...,...,...,...
740746,2026-06-14 09:51:00+00:00,ALB,ALBANY COUNTY ARPT,US,65.0,56.0,4.0,0.0
740747,2026-06-14 10:51:00+00:00,ALB,ALBANY COUNTY ARPT,US,68.0,57.0,5.0,0.0
740748,2026-06-14 11:51:00+00:00,ALB,ALBANY COUNTY ARPT,US,70.0,58.0,7.0,0.0
740749,2026-06-14 12:51:00+00:00,ALB,ALBANY COUNTY ARPT,US,75.0,59.0,6.0,0.0
740750,2026-06-14 13:51:00+00:00,ALB,ALBANY COUNTY ARPT,US,76.0,59.0,8.0,0.0

In [ ]:
# some subsection code
a = [1, 2, 3, 4, 5]
[i + 2 for i in a]

### Another content subsection
Keep up the good work! A note, *try to avoid using code comments as narrative*, and instead let them only exist as brief clarifications where necessary.

## Your second content section
Here we can move on to our second objective, and we can demonstrate...

### A subsection to the second section

#### a quick demonstration

##### of further and further

###### header levels

as well as $m = a * t / h$ text! Similarly, you have access to other $\LaTeX$ equation [**functionality**](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Typesetting%20Equations.html) via MathJax:

\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{y} & = \rho x - y - xz \\
\dot{z} & = -\beta z + xy
\end{align}

Check out [**any number of helpful Markdown resources**](https://www.markdownguide.org/basic-syntax/) for further customizing your notebooks and the [**MyST Syntax Overview**](https://mystmd.org/guide/syntax-overview) for MyST-specific formatting information. Don't hesitate to ask questions if you have problems getting it to look *just right*.

## Last Section

You can add [admonitions using MyST syntax](https://mystmd.org/guide/admonitions):

:::{note}
Your relevant information here!
:::

Some other admonitions you can put in ([there are 10 total](https://mystmd.org/guide/admonitions#admonitions-list)):

:::{hint}
A helpful hint.
:::

:::{warning}
Be careful!
:::

:::{danger}
Scary stuff be here.
:::

We also suggest checking out MyST's [brief demonstration](https://mystmd.org/guide/notebook-configuration#notebook-cell-tags) on adding cell tags to your cells in Jupyter Notebook, Lab, or manually. See [this table](https://mystmd.org/guide/notebook-configuration#tbl-notebook-cell-tags) for a list of supported cell tags, which you can use to customize how your code content is displayed and even [demonstrate errors](https://mystmd.org/guide/execute-notebooks#allow-a-code-cell-to-error-without-failing-the-build) without altogether crashing our loyal army of machines!

---

## Summary
Add one final `---` marking the end of your body of content, and then conclude with a brief single paragraph summarizing at a high level the key pieces that were learned and how they tied to your objectives. Look to reiterate what the most important takeaways were.

### What's next?
Let Jupyter book tie this to the next (sequential) piece of content that people could move on to down below and in the sidebar. However, if this page uniquely enables your reader to tackle other nonsequential concepts throughout this book, or even external content, link to it here!

## Resources and references
Finally, be rigorous in your citations and references as necessary. Give credit where credit is due. Also, feel free to link to relevant external material, further reading, documentation, etc. Then you're done! Give yourself a quick review, a high five, and send us a pull request. A few final notes:
 - `Kernel > Restart Kernel and Run All Cells...` to confirm that your notebook will cleanly run from start to finish
 - `Kernel > Restart Kernel and Clear All Outputs...` before committing your notebook, our machines will do the heavy lifting
 - Take credit! Provide author contact information if you'd like; if so, consider adding information here at the bottom of your notebook
 - Give credit! Attribute appropriate authorship for referenced code, information, images, etc.
 - Only include what you're legally allowed: **no copyright infringement or plagiarism**
 
Thank you for your contribution!